In [2]:
!pip install --upgrade vaex

  Using cached vaex-4.16.0-py3-none-any.whl (4.7 kB)
  Using cached vaex_astro-0.9.3-py3-none-any.whl (20 kB)
  Using cached vaex_core-4.16.1-cp39-cp39-win_amd64.whl (2.0 MB)
  Using cached vaex_jupyter-0.8.1-py3-none-any.whl (43 kB)
  Using cached vaex_hdf5-0.14.1-py3-none-any.whl (16 kB)
  Using cached vaex_ml-0.18.1-py3-none-any.whl (58 kB)
  Using cached vaex_server-0.8.1-py3-none-any.whl (23 kB)
  Using cached vaex_viz-0.5.4-py3-none-any.whl (19 kB)
  Using cached astropy-5.2.1-cp39-cp39-win_amd64.whl (6.6 MB)
  Using cached frozendict-2.3.4-cp39-cp39-win_amd64.whl (35 kB)
  Using cached filelock-3.9.0-py3-none-any.whl (9.7 kB)
  Using cached progressbar2-4.2.0-py2.py3-none-any.whl (27 kB)
  Using cached bqplot-0.12.36-py2.py3-none-any.whl (1.2 MB)
  Using cached ipyvuetify-1.8.4-py2.py3-none-any.whl (11.7 MB)
  Using cached ipympl-0.9.2-py2.py3-none-any.whl (510 kB)
  Using cached ipyleaflet-0.17.2-py3-none-any.whl (3.7 MB)
  Using cached xarray-2022.12.0-py3-none-any.whl (969 kB

* https://github.com/vaexio/vaex/issues/498
* load data example https://vaex.readthedocs.io/en/latest/datasets.html
* Vaex supports several data sources: https://vaex.readthedocs.io/en/latest/guides/io.html

In [30]:
import vaex
import time
import tensorflow as tf
import pandas as pd

In [10]:
vaex.__version__

{'vaex': '4.16.0',
 'vaex-core': '4.16.1',
 'vaex-viz': '0.5.4',
 'vaex-hdf5': '0.14.1',
 'vaex-server': '0.8.1',
 'vaex-astro': '0.9.3',
 'vaex-jupyter': '0.8.1',
 'vaex-ml': '0.18.1'}

In [3]:
df = vaex.from_csv(r'titanic.csv')
df

#    PassengerId    Survived    Pclass    Name                                                 Sex     Age    SibSp    Parch    Ticket            Fare     Cabin    Embarked
0    1              0           3         Braund, Mr. Owen Harris                              male    22.0   1        0        A/5 21171         7.25     --       S
1    2              1           1         'Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0   1        0        PC 17599          71.2833  C85      C
2    3              1           3         Heikkinen, Miss. Laina                               female  26.0   0        0        STON/O2. 3101282  7.925    --       S
3    4              1           1         Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0   1        0        113803            53.1     C123     S
4    5              0           3         Allen, Mr. William Henry                             male    35.0   0        0        373450            8.05     --       S
...  ...            ...         ...       ...                                                  ...     ...    ...      ...      ...               ...      ...      ...
886  887            0           2         Montvila, Rev. Juozas                                male    27.0   0        0        211536            13.0     --       S
887  888            1           1         Graham, Miss. Margaret Edith                         female  19.0   0        0        112053            30.0     B42      S
888  889            0           3         Johnston, Miss. Catherine Helen "Carrie"             female  nan    1        2        W./C. 6607        23.45    --       S
889  890            1           1         Behr, Mr. Karl Howell                                male    26.0   0        0        111369            30.0     C148     C
890  891            0           3         Dooley, Mr. Patrick                                  male    32.0   0        0        370376            7.75     --       Q

# Read from parquet

In [46]:
%%time
dfAll = vaex.open('userdata1.parquet')
dfAll

Wall time: 4.03 ms


#    registration_dttm    id    first_name    last_name    email                     gender    ip_address       cc                country       birthdate    salary     title                   comments
0    2016-02-03 07:55:29  1     Amanda        Jordan       ajordan0@com.com          Female    1.197.201.2      6759521864920116  Indonesia     3/8/1971     49756.53   Internal Auditor        1E+02
1    2016-02-03 17:04:03  2     Albert        Freeman      afreeman1@is.gd           Male      218.111.175.34                     Canada        1/16/1968    150280.17  Accountant IV
2    2016-02-03 01:09:31  3     Evelyn        Morgan       emorgan2@altervista.org   Female    7.161.136.94     6767119071901597  Russia        2/1/1960     144972.51  Structural Engineer
3    2016-02-03 00:36:21  4     Denise        Riley        driley3@gmpg.org          Female    140.35.109.83    3576031598965625  China         4/8/1997     90263.05   Senior Cost Accountant
4    2016-02-03 05:05:31  5     Carlos        Burns        cburns4@miitbeian.gov.cn            169.113.235.40   5602256255204850  South Africa               --
...  ...                  ...   ...           ...          ...                       ...       ...              ...               ...           ...          ...        ...                     ...
995  2016-02-03 10:30:59  996   Dennis        Harris       dharrisrn@eepurl.com      Male      178.180.111.236  374288806662929   Greece        7/8/1965     263399.54  Editor
996  2016-02-03 17:16:53  997   Gloria        Hamilton     ghamiltonro@rambler.ru    Female    71.50.39.137                       China         4/22/1975    83183.54   VP Product Management
997  2016-02-03 05:02:20  998   Nancy         Morris       nmorrisrp@ask.com                   6.188.121.221    3553564071014997  Sweden        5/1/1979     --         Junior Executive
998  2016-02-03 02:41:32  999   Annie         Daniels      adanielsrq@squidoo.com    Female    97.221.132.35    30424803513734    China         10/9/1991    18433.85   Editor                  ​
999  2016-02-03 09:52:18  1000  Julie         Meyer        jmeyerrr@flavors.me       Female    217.1.147.132    374288099198540   China                      222561.13

In [47]:
%%time
dfAll = vaex.open('userdata1.parquet')
for par in ['userdata2.parquet','userdata3.parquet','userdata4.parquet','userdata5.parquet']:
    dfs = vaex.open(par)
    dfAll = vaex.concat([dfs,dfAll])

Wall time: 494 ms


In [48]:
dfAll

#      registration_dttm    id    first_name    last_name    email                          gender    ip_address       cc                 country        birthdate    salary     title                   comments
0      2016-02-04 10:34:07  1     Kelly         Ortiz        kortiz0@omniture.com           Female    252.115.158.159  3537905681760845   Russia         4/23/1980    277302.99  Nurse
1      2016-02-04 22:54:01  2     Sharon        Carroll      scarroll1@disqus.com           Female    29.217.252.62    56022458507191696  Indonesia      8/28/1992    209258.05  Recruiter               åß∂ƒ©˙∆˚¬…æ
2      2016-02-04 17:59:50  3     Ruth          Ross         rross2@cbc.ca                  Female    220.224.80.32    3589642396435648   Benin          6/13/1994    18270.7    Design Engineer
3      2016-02-04 16:03:17  4     Kelly         Meyer        kmeyer3@cornell.edu            Female    255.65.123.124                      Philippines    1/6/1967     17485.27   Cost Accountant
4      2016-02-04 11:12:24  5     Irene         Jordan       ijordan4@pagesperso-orange.fr  Female    162.57.23.136    3576848317807089   United States  1/4/1997     163979.38  Programmer Analyst III
...    ...                  ...   ...           ...          ...                            ...       ...              ...                ...            ...          ...        ...                     ...
4,995  2016-02-03 10:30:59  996   Dennis        Harris       dharrisrn@eepurl.com           Male      178.180.111.236  374288806662929    Greece         7/8/1965     263399.54  Editor
4,996  2016-02-03 17:16:53  997   Gloria        Hamilton     ghamiltonro@rambler.ru         Female    71.50.39.137                        China          4/22/1975    83183.54   VP Product Management
4,997  2016-02-03 05:02:20  998   Nancy         Morris       nmorrisrp@ask.com                        6.188.121.221    3553564071014997   Sweden         5/1/1979     --         Junior Executive
4,998  2016-02-03 02:41:32  999   Annie         Daniels      adanielsrq@squidoo.com         Female    97.221.132.35    30424803513734     China          10/9/1991    18433.85   Editor                  ​
4,999  2016-02-03 09:52:18  1000  Julie         Meyer        jmeyerrr@flavors.me            Female    217.1.147.132    374288099198540    China                       222561.13

# Read from huge data on S3

In [11]:
%%time
dfs = vaex.open('s3://vaex/airline/us_airline_data_1988_2018.hdf5?anon=true')
dfs

Wall time: 22.3 s


#            Year    Month    DayOfMonth    DayOfWeek    UniqueCarrier    TailNum    FlightNum    Origin    Dest    CRSDepTime    DepTime    DepDelay    TaxiOut    TaxiIn    CRSArrTime    ArrTime    ArrDelay    Cancelled    CancellationCode    Diverted    CRSElapsedTime    ActualElapsedTime    AirTime    Distance    CarrierDelay    WeatherDelay    NASDelay    SecurityDelay    LateAircraftDelay
0            1988    1        8             5            PI               None       930          BGM       ITH     1525          1532       7           --         --        1545          1555       10          0            None                0           20                23                   --         32          --              --              --          --               --
1            1988    1        9             6            PI               None       930          BGM       ITH     1525          1522       -3          --         --        1545          1535       -10         0            None                0           20                13                   --         32          --              --              --          --               --
2            1988    1        10            7            PI               None       930          BGM       ITH     1525          1522       -3          --         --        1545          1534       -11         0            None                0           20                12                   --         32          --              --              --          --               --
3            1988    1        11            1            PI               None       930          BGM       ITH     1525          --         --          --         --        1545          --         --          1            None                0           20                --                   --         32          --              --              --          --               --
4            1988    1        12            2            PI               None       930          BGM       ITH     1525          1524       -1          --         --        1545          1540       -5          0            None                0           20                16                   --         32          --              --              --          --               --
...          ...     ...      ...           ...          ...              ...        ...          ...       ...     ...           ...        ...         ...        ...       ...           ...        ...         ...          ...                 ...         ...               ...                  ...        ...         ...             ...             ...         ...              ...
183,821,921  2018    12       27            4            DL               N705TW     864          JFK       SLC     935           929        -6          28         9         1311          1230       -41         0            None                0           336               301                  264        1990        --              --              --          --               --
183,821,922  2018    12       27            4            DL               N336NB     865          MSP       SLC     1035          1030       -5          14         10        1240          1214       -26         0            None                0           185               164                  140        991         --              --              --          --               --
183,821,923  2018    12       27            4            DL               N945DN     866          DEN       MSP     1054          1100       6           10         5         1353          1350       -3          0            None                0           119               110                  95         680         --              --              --          --               --
183,821,924  2018    12       27            4            DL               N945DN     866          MSP       DEN     850           850        0           15         

In [13]:
dfs.shape

(183821926, 29)

In [15]:
dfs['Month'].values

array([ 1,  1,  1, ..., 12, 12, 12], dtype=int8)

In [16]:
len(dfs['Month'].values)

183821926

In [18]:
label = tf.convert_to_tensor(dfs['Month'].values, dtype=tf.float32)
label

<tf.Tensor: shape=(183821926,), dtype=float32, numpy=array([ 1.,  1.,  1., ..., 12., 12., 12.], dtype=float32)>

In [25]:
features = tf.convert_to_tensor(dfs[['ArrTime','Cancelled','Diverted','ActualElapsedTime']].values, dtype=tf.float32)
features

<tf.Tensor: shape=(183821926, 4), dtype=float32, numpy=
array([[1555.,    0.,    0.,   23.],
       [1535.,    0.,    0.,   13.],
       [1534.,    0.,    0.,   12.],
       ...,
       [1350.,    0.,    0.,  110.],
       [ 951.,    0.,    0.,  121.],
       [1703.,    0.,    0.,  123.]], dtype=float32)>

In [27]:
#set up the model 
model = tf.keras.Sequential([
  tf.keras.layers.Dense(2, activation=tf.keras.activations.relu), 
  tf.keras.layers.Dense(1, activation=tf.keras.activations.sigmoid) 
])

# Compile the model
model.compile(loss=tf.keras.losses.categorical_crossentropy,
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])


# Fit the model
history = model.fit(features, label, epochs=2)

Epoch 1/2
   6904/5744436 [..............................] - ETA: 2:32:25 - loss: 0.0000e+00 - accuracy: 0.0834

KeyboardInterrupt: 